# Site settings
title:          Bits and Ops
description:    "Miko's blog about devops and programming"
baseurl:        "/"
url:            "https://www.gasior.dev"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Mikolaj Gasior
  url:          https://www.gasior.dev
  email:        nospam@gasior.dev

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       15

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
